### ISSUE TITLE
I want to ask to you

### ISSUE THREAD

**Issue by Zedvy** [AhmedMinegames/MinegamesAntiCheat#1]
Do you think this is able to support kernel injection?

**Comment by AhmedMinegames** [comment]
even if i did that would be useless..... cause you are operating in usermode anyway and also because of the limitation in C#, for example i made the anti dll injector lock down the entire loading instead of checking the dll which may stop legit dll's from loading and may cause a crash (because you can't hook functions in C# to validate the dll, you can just patch function address bytes to make it fail) if you want to really protect your .NET App from cheaters (assuming that nobody will try to decompile and deobfuscate it, and will try to attack it directly) then make your Anti-Cheat in C++ Dll and then import it from your C# Application and check the hash of the dll, cause literally all you can do in C# is protect values and check for some debuggers, nothing else, but you can just patch LoadLibraryA and LoadLibraryW which C# Dll's don't use to load it's dependencies, which will stop some script kiddies that use automated tools (like Cheat Engine, which uses these functions to load it's speedhack module).
